name: Check Lobe-Chat Release

on:
  schedule:
    - cron: '15 15 * * *'   # 每天北京时间23点5分触发
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # 允许使用 GITHUB_TOKEN 推送到当前仓库

      - name: Get latest release of lobehub/lobe-chat
        id: get_release
        run: |
          # 用 GitHub API 获取最新 tag
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/lobehub/lobe-chat/releases/latest" | jq -r '.tag_name')
          echo "latest_release=$LATEST_RELEASE" >> $GITHUB_OUTPUT

      - name: Compare with previous release
        id: compare_release
        run: |
          LATEST_RELEASE="${{ steps.get_release.outputs.latest_release }}"
          echo "Latest release in lobehub/lobe-chat: $LATEST_RELEASE"

          PREV_RELEASE="unknown"
          if [ -f .last_release ]; then
            PREV_RELEASE=$(cat .last_release)
          fi
          echo "Previous release: $PREV_RELEASE"

          if [ "$LATEST_RELEASE" != "$PREV_RELEASE" ]; then
            echo "Detected a new release!"
            echo "$LATEST_RELEASE" > .last_release
            echo "UPDATED=true" >> $GITHUB_ENV
          else
            echo "No new release found."
            echo "UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Write .build_docker_clerk
        run: |
          if [ "${{ env.UPDATED }}" = "true" ]; then
            echo "1" > .build_docker_clerk
          else
            echo "0" > .build_docker_clerk
          fi

      - name: Commit and push changes
        # 只有在 compare_release 步骤中标记 UPDATED=true 后才执行提交 .last_release 的逻辑；
        # 但无论是否更新，这里都会有 .build_docker_clerk 的写入
        run: |
          # 配置 Git 用户信息
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 加入暂存区
          git add .last_release .build_docker_clerk || true

          # 判断是否有改动
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "chore: update tracking files (release: ${{ steps.get_release.outputs.latest_release }}, docker_clerk: ${{ env.UPDATED }})"
            git push
          fi
        shell: bash
